10/14/2022 01:31:27 - INFO - __main__ - ----------------------------------------------------------------------------------------------------
10/14/2022 01:31:27 - INFO - __main__ - Training models on Vision-Language continual learning tasks...
10/14/2022 01:31:27 - INFO - __main__ - ----------------------------------------------------------------------------------------------------
10/14/2022 01:31:27 - INFO - __main__ - Training vilt model on task #1: VQAv2
10/14/2022 01:31:28 - INFO - data.visionlanguage_datasets.vqa_dataset - Creating VQAv2 train dataloader with batch size of 32
10/14/2022 01:31:30 - INFO - data.visionlanguage_datasets.vqa_dataset - Loaded VQAv2 train dataset, with 443757 examples
10/14/2022 01:31:30 - INFO - data.visionlanguage_datasets.vqa_dataset - Creating VQAv2 val dataloader with batch size of 32
10/14/2022 01:31:31 - INFO - data.visionlanguage_datasets.vqa_dataset - Loaded VQAv2 val dataset, with 214354 examples
Training epoch 1:   0% 0/13868 [00:00<?, ?it/s]Training epoch 1:   0% 0/13868 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/home1/caiyulia/.conda/envs/climb/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home1/caiyulia/.conda/envs/climb/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/project/rostamim_919/caiyulia/Multi-Dytox/src/run.py", line 249, in <module>
    main()
  File "/project/rostamim_919/caiyulia/Multi-Dytox/src/run.py", line 185, in main
    ewc=None)
  File "./train/train_vqa.py", line 264, in train
    print(" the task token is " + str(model.task_token.data))
  File "/home1/caiyulia/.conda/envs/climb/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1178, in __getattr__
    type(self).__name__, name))
AttributeError: 'ViltContinualLearner' object has no attribute 'task_token'
